### ISSUE TITLE
Revise the checklist procedure for appending Anaconda3 to the PATH

### ISSUE THREAD

**Issue by somexpert** [unt-carpentries/2018-03-14-unt-swc#14]
We found that the instructions needed to be revised in order to work. For one thing, the default installation location is different, but also we found we have to append to .profile rather than .bashrc. We should probably have the user check the location by typing `which python` in the anaconda prompt and then using that to set the PATH.

**Comment by somexpert** [comment]
let's also use absolute paths for the destination file so the location doesn't matter

**Comment by ldko** [comment]
Note, Anaconda strongly advises against adding Anaconda to the path https://github.com/swcarpentry/python-novice-inflammation/issues/485#issuecomment-374191140. Rather, the `activate` script should be used.

**Comment by somexpert** [comment]
ah ok, well I'll test that out and update the instructions on our list accordingly

**Comment by msarahan** [comment]
There is a distinction between Windows and Linux/Mac.  On Linux/Mac, I find it is mostly OK to add anaconda to PATH.  We've seen some issues with KDE scripts that are written in a way that ends up finding Anaconda's python rather than the expected system python, and stuff breaks.  However, that's a very small number of issues.  I haven't seen many issues on Mac with adding anaconda to PATH.

On Windows, it is very different.  Because PATH is used to resolve DLL dependencies, and not just EXE's, setting PATH has more drastic consequences.  Anaconda's MKL libraries can conflict with other programs that use MKL, for example.  It is best in these cases to keep as much off of PATH as possible, but provide shortcuts (like anaconda prompt, or perhaps a bash equivalent) that drop people into an activated prompt.

If you are setting .bashrc for bash in Windows, that is going to be much safer than modifying PATH globally in windows, because bash is already a compartmentalized environment.  I'd go so far as to call that highly unlikely to cause problems.

**Comment by ldko** [comment]
Thanks for the explanation/clarification @msarahan !

**Comment by somexpert** [comment]
Thank you @msarahan! Can use all the help I can get when it comes to Windows. Not my forte :smile:

So I will adjust our instructions then to have the user look at where Anaconda is installed on their system with `where python` in the anaconda prompt, then use that to enter the following in their git bash terminal:
`echo "source [absolute path to anaconda installation]/Scripts/activate" >> ~/.bashrc`

**Comment by somexpert** [comment]
This was resolved in #15
